<?php

namespace Database\Seeders;

// use App\Models\StudentClass;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $teachers = [
        // ['name' => 'Ade Putra Ananda', 'email' => 'adeputra8935@gmail.com'],
        // ['name' => 'Agung Pramono', 'email' => 'agunkpr@yahoo.com'],
        // ['name' => 'Agus Tri Maulidyanto', 'email' => 'agustrimaulidyanto989877@gmail.com'],
        // ['name' => 'Agustini Mardelyni', 'email' => 'agustinimardelyni@gmail.com'],
        // ['name' => 'Akhmad Nahyani', 'email' => 'akhmad_nahyani@yahoo.co.id'],
        // ['name' => 'Alwi Nur Faizal', 'email' => 'alwinurfaizal@gmail.com'],
        // ['name' => 'Aminah Gultom', 'email' => 'aminahgultom@gmail.com'],
        // ['name' => 'Amir Hamzah', 'email' => 'hzhamis28@gmail.com'],
        // ['name' => 'Amrul Khairullah', 'email' => 'amroel@gmail.com'],
        // ['name' => 'Ana Amalia Islami', 'email' => 'anaamaliaislami@gmail.com'],
        // ['name' => 'Anna Mailani', 'email' => 'anna.mailani@gmail.com'],
        // ['name' => 'Arief Barwadi', 'email' => 'arief.bawardi@gmail.com'],
        // ['name' => 'Arlin Nuari', 'email' => 'arlynnuary@gmail.com'],
        // ['name' => 'Arman Rivai', 'email' => 'armanrivay@gmail.com'],
        // ['name' => 'Asep Dody Junaedi Mansur', 'email' => 'asepjunaedi1966@gmail.com'],
        // ['name' => 'Atik Sukmawijaya', 'email' => 'sukmawijaya.atik@gmail.com'],
        // ['name' => 'Atik Yuli Hastuty', 'email' => 'atikpurnomo@ymail.com'],
        // ['name' => 'Baidha Azra', 'email' => 'baidhaazra.ba@gmail.com'],
        // ['name' => 'Bambang Susanto', 'email' => 'bamssusanto10@gmail.com'],
        // ['name' => 'Bintang Ria Sihotang', 'email' => 'bintang_sihotang@yahoo.com'],
        // ['name' => 'Bukari', 'email' => 'bukariesemka1@gmail.com'],
        // ['name' => 'Citra Nindi Umayah', 'email' => 'citranidi9@gmail.com'],
        // ['name' => 'Dedy Subroto', 'email' => 'deday7@gmail.com'],
        // ['name' => 'Dekson Yoni Toto', 'email' => 'deksonjonny@gmail.com'],
        // ['name' => 'Dewi Nurmiati', 'email' => 'dewinurmiati42@gmail.com'],
        // ['name' => 'Dwinta Saptiwi Putri', 'email' => 'dwintasaptiwip@yahoo.com'],
        // ['name' => 'Eko Pujiharso', 'email' => 'eko.pujiharso@yahoo.co.id'],
        // ['name' => 'Endah Kemalasari', 'email' => 'endahkemalasari@yahoo.co.id'],
        // ['name' => 'Endah Sri Wahyuni', 'email' => 'endahdara630@gmail.com'],
        // ['name' => 'Erfan Wahyu Utomo', 'email' => 'erfan.9214@studentsunnes.ac.id'],
        // ['name' => 'Faishal Azhar', 'email' => 'faishal.azhar@gmail.com'],
        // ['name' => 'Fauziah Chair Fadil', 'email' => 'fauziah_fadil22@yahoo.co.id'],
        // ['name' => 'Giri Wicaksono', 'email' => 'rec.giriwcksn@gmail.com'],
        // ['name' => 'Hanif', 'email' => 'hanifhbasri@gmail.com'],
        // ['name' => 'Hardy Widjaya', 'email' => 'widjaya.hardy@yahoo.c.o.id'],
        // ['name' => 'Harry Nugroho', 'email' => 'harrynugroho81@gmail.com'],
        // ['name' => 'Hasan Bakri Usman Lamatungga', 'email' => 'hasanbul@ymail.com'],
        // ['name' => 'Hendid Tiga Riyanto', 'email' => 'hendid88@gmail.com'],
        // ['name' => 'Ihsan Ruliyanda', 'email' => 'irguci@gmail.com'],
        // ['name' => 'Isya Anshori', 'email' => 'ianshori331@gmail.com'],
        // ['name' => 'Jeffrey Immanuel Hasudungan N', 'email' => 'noel.na70@gmail.com'],
        // ['name' => 'Jumiyati', 'email' => 'jumiyati@smkn1cikarangbarat.sch.id'],
        // ['name' => 'Kuwat', 'email' => 'kuwatriyanto@yahoo.com'],
        // ['name' => 'Latifah Nurul Hidayati', 'email' => 'tifanurul05@gmail.com'],
        // ['name' => 'Leti Yulieti', 'email' => 'letiyulieti66@gmail.com'],
        // ['name' => 'Luke Nugroho', 'email' => 'luke.nugroho23@gmail.com'],
        // ['name' => 'Marlon Napitupulu', 'email' => 'marlon_pprn@yahoo.co.id'],
        // ['name' => 'Martua Sinaga', 'email' => 'sinagamartua@gmail.com'],
        // ['name' => 'Mohamad Rahino', 'email' => 'oto_smkn_01@yahoo.co.id'],
        // ['name' => 'Muhammad Fikri Insan Ridho', 'email' => 'murisandho20@gmail.com'],
        // ['name' => 'Muhammad Rizki', 'email' => 'muhammadrizki0192@gmail.com'],
        // ['name' => 'Muji Antoro', 'email' => 'mujiantorro@gmail.com'],
        // ['name' => 'Mutmainnah Naiyan', 'email' => 'mutmainahnaiyan@gmail.com'],
        // ['name' => 'Nabil Ridho', 'email' => 'nabilridhoo@gmail.com'],
        // ['name' => 'Nina Noverita', 'email' => 'ninanoverita@gmail.com'],
        // ['name' => 'Nina Rosiana', 'email' => 'ninarosiana1985@gmail.com'],
        // ['name' => 'Novi Ari Wibowo', 'email' => 'novari.dev@gmail.com'],
        // ['name' => 'Noviar Pahlawanti', 'email' => 'noviar83@gmail.com'],
        // ['name' => 'Nurmiyati', 'email' => 'nurmiyatismk1@yahoo.co.id'],
        // ['name' => 'P. Antonia Ginting', 'email' => 'ni20a@yahoo.com'],
        // ['name' => 'Purwanto', 'email' => 'purwanto_150364@yahoo.co.id'],
        // ['name' => 'R. Wisnu Sarjono', 'email' => 'wisnu221@yahoo.com'],
        // ['name' => 'Rachmat Hidayat', 'email' => 'rhidayat0405@gmail.com'],
        // ['name' => 'Rianti Mandasari', 'email' => 'riantimandasari95@gmail.com'],
        // ['name' => 'Ridho Achmad Fikri Madani', 'email' => 'ridhoachmadfikri@gmail.com'],
        // ['name' => 'Rina Rachminingsih', 'email' => 'rinarachminingsih27@gmail.com'],
        // ['name' => 'Rio Haryanto', 'email' => 'rioharyanto1288@gmail.com'],
        // ['name' => 'Ronald Pakpahan', 'email' => 'ronaldpakpahan@ymail.com'],
        // ['name' => 'Rukman', 'email' => 'rukman12@ymail.com'],
        // ['name' => 'Rustama', 'email' => 'roestama_smkn1jkt@yahoo.co.id'],
        // ['name' => 'Silvia Fajriani', 'email' => 'silvia.fajri@gmail.com'],
        // ['name' => 'Siti Hajar Muyasaroh', 'email' => 'sitihajarmuyasaroh@gmail.com'],
        // ['name' => 'Siti Iswah Mawadah', 'email' => 'iswahmawaddah10@gmail.com'],
        // ['name' => 'Sri Raharjo', 'email' => 'jo2harjo@gmail.com'],
        // ['name' => 'Sudirman', 'email' => 'sudirmanilham@gmail.com'],
        // ['name' => 'Sugiyani', 'email' => 'bsugiyani@yahoo.co.id'],
        // ['name' => 'Sukmianih', 'email' => 'anihsukmianih@yahoo.co.id'],
        // ['name' => 'Sumiasih', 'email' => 'sumiasihasyik@gmail.com'],
        // ['name' => 'Sunariah', 'email' => 'sunariah56@yahoo.com'],
        // ['name' => 'Sunaryo', 'email' => 'sunaryo.7073@gmail.com'],
        // ['name' => 'Sutris Janta Surbakti', 'email' => 'jantasurbakti@gmail.com'],
        // ['name' => 'Syarifudin', 'email' => 'syarifudin.531509@gmail.com'],
        // ['name' => 'Tias Andriani', 'email' => 'tiya5642@yahoo.com'],
        // ['name' => 'Tri Oke Mahendra', 'email' => 'oketri86@gmail.com'],
        // ['name' => 'Udin Komarudin', 'email' => 'udin_68@yahoo.com'],
        // ['name' => 'Untung Sarwo Prajogo', 'email' => 'gunnis69@yahoo.co.id'],
        // ['name' => 'Vouzya Hamdi', 'email' => 'vauzyahamdi@gmail.com'],
        // ['name' => 'Wahyu Purwaningsih', 'email' => 'ayu.purwa@gmail.com'],
        // ['name' => 'Wanto Ari Wibowo', 'email' => 'wantoncm@gmail.com'],
        // ['name' => 'Windi Fauziah', 'email' => 'windiifauziah@gmail.com'],
        // ['name' => 'Yarneli', 'email' => 'yarnelipkn@gmail.com'],
        // ['name' => 'Yuli Astuti', 'email' => 'yuliastutiii@yahoo.com'],
        // ['name' => 'Yunelmi', 'email' => 'yunelmi@gmail.com'],
        // ['name' => 'Yuwita Novyanti', 'email' => 'yuwita.novyanti@gmail.com'],
        // ['name' => 'Zainal Abidin', 'email' => 'jenal6087@gmail.com'],
        // ];
        $teachers = [
            [
                'class' => 'X DPIB 1',
                'name' => 'Agustini Mardelyni, S.Pd.',
                'uuid' => '19910817 2022212008',
                'classroom' => 'R.AOI',
            ],
            [
                'class' => 'X DPIB 2',
                'name' => 'Untung Sarwo Prayogo, S.Pd.',
                'uuid' => '19690327 2008011013',
                'classroom' => 'R-305',
            ],
            [
                'class' => 'X TKP 1',
                'name' => 'Windi Fauziah, S.Pd.',
                'uuid' => '19950325 2022212004',
                'classroom' => 'R.A04',
            ],
            [
                'class' => 'X TKP 2',
                'name' => 'Muhammad Rizki, S.Pd.',
                'uuid' => '19920701 2022211003',
                'classroom' => 'BENGKEL BANGUNAN 1',
            ],
            [
                'class' => 'XI DPIB 1',
                'name' => 'Nia Wtdyaningsih',
                'uuid' => '198501182024212013',
                'classroom' => 'R.A02',
            ],
            [
                'class' => 'XI DPIB 2',
                'name' => 'Baidha Azra, S.Pd.',
                'uuid' => '19930415 2019032008',
                'classroom' => 'R.303',
            ],
            [
                'class' => 'XI TKP 1',
                'name' => 'Ana Amalia Islami, ST.',
                'uuid' => '19940503 2019032025',
                'classroom' => 'R.404',
            ],
            [
                'class' => 'XI TKP 2',
                'name' => 'Fauziah Chair Fadil, S.Pd.',
                'uuid' => '199111222023212030',
                'classroom' => 'R.A05',
            ],
            [
                'class' => 'X TITL 1',
                'name' => 'Hetiny Muthia Rahmy, M.Pd.',
                'uuid' => '199311262022212005',
                'classroom' => 'BENGKEL LISTRIK 5',
            ],
            [
                'class' => 'X TITL 2',
                'name' => 'Mutmainah Naiyan, S.Pd.',
                'uuid' => '199401052023212036',
                'classroom' => 'R.A08',
            ],
            [
                'class' => 'X TITL 3',
                'name' => 'Alwi Nur Faizal, S.Pd.',
                'uuid' => '19920112 2022211002',
                'classroom' => 'R-A09',
            ],
            [
                'class' => 'XI TITL 1',
                'name' => 'Neneng Desi Mulawati',
                'uuid' => '198512172024212017',
                'classroom' => 'BENGKEL LISTRIK 4',
            ],
            [
                'class' => 'XI TITL 2',
                'name' => 'Silvia Fajriani, S.Pd',
                'uuid' => '19941026 2022212006',
                'classroom' => 'BENGKEL LISTRIK 3',
            ],
            [
                'class' => 'XI TITL 3',
                'name' => 'Noviar Pahlawanti, S.Pd',
                'uuid' => '19831110 202212015',
                'classroom' => 'R.AIO',
            ],
            [
                'class' => 'X TP 1',
                'name' => 'Ihsan Ruliyanda, S.Pd',
                'uuid' => '19920915 2022211001',
                'classroom' => 'BENGKEL MESIN 1',
            ],
            [
                'class' => 'X TP 2',
                'name' => 'Luke Nugroho, S.Pd',
                'uuid' => '19920523 2020121019',
                'classroom' => 'R.B06',
            ],
            [
                'class' => 'X DGM',
                'name' => 'Amir Hamzah, S.Pd',
                'uuid' => '198907242023211020',
                'classroom' => 'R.COI',
            ],
            [
                'class' => 'XI TP 1',
                'name' => 'Drs. Asep Dody Junaedi Mansur',
                'uuid' => '19660923 2016111002',
                'classroom' => 'BENGKEL MESIN 2',
            ],
            [
                'class' => 'XI TP 2',
                'name' => 'Gatot Sutiono',
                'uuid' => '197201132024211002',
                'classroom' => 'R.C02',
            ],
            [
                'class' => 'XI DGM',
                'name' => 'Nabil Ridho, S.Pd',
                'uuid' => '19950315 2022211003',
                'classroom' => 'R.C03',
            ],
            [
                'class' => 'X TKR',
                'name' => 'Endah Kemalasari, S.Pd',
                'uuid' => '19790418 2014082002',
                'classroom' => 'R.BOI',
            ],
            [
                'class' => 'XI TKR 1',
                'name' => 'Zainal Abidin, S.Pd.l.',
                'uuid' => '19870111 2020121003',
                'classroom' => 'R.B02',
            ],
            [
                'class' => 'XI TKR 2',
                'name' => 'Hardy Widjaya, SPd',
                'uuid' => '197912042014121001',
                'classroom' => 'R.B03',
            ],
            [
                'class' => 'X TKJ 1',
                'name' => 'Angelina Taruli R. Togatorop',
                'uuid' => '199010102023212078',
                'classroom' => 'R.202',
            ],
            [
                'class' => 'X TKJ 2',
                'name' => 'R. Wisnu Sarjono, s.Pd, MT',
                'uuid' => '19720824 2008011010',
                'classroom' => 'R.203',
            ],
            [
                'class' => 'XI TKJ',
                'name' => 'Isya Anshori, M.Pd',
                'uuid' => '199103062023211022',
                'classroom' => 'R.406',
            ],
            [
                'class' => 'X RPL',
                'name' => 'Alzaro Rashad Prakas, S.Tr.',
                'uuid' => '1030397',
                'classroom' => 'R.205',
            ],
            [
                'class' => 'X SIJA',
                'name' => 'Harry Nugroho, S.Kom',
                'uuid' => '19811206 2022211006',
                'classroom' => 'R.206',
            ],
            [
                'class' => 'XI RPL',
                'name' => 'Wanto Ari Wibowo, S.Kom',
                'uuid' => '19840707 2022211013',
                'classroom' => 'R.405',
            ],
            [
                'class' => 'XI SIJA',
                'name' => 'Ester Suryani Banjar Nahor',
                'uuid' => '198809092024212041',
                'classroom' => 'R.408',
            ],
            [
                'class' => 'XII SIJA',
                'name' => 'Sudirwan, M.Pd.',
                'uuid' => '196812232022211002',
                'classroom' => 'R 103',
            ],
            [
                'class' => 'X DKV',
                'name' => 'Siti Iswah Mawadah, S.Pd',
                'uuid' => '19931126 2022212005',
                'classroom' => 'R 207',
            ],
            [
                'class' => 'XI DKV',
                'name' => 'Arlin Nuari, S.Pd',
                'uuid' => '19890104 2020122015',
                'classroom' => 'R 307',
            ],
        ];

        foreach ($teachers as $t) {
            DB::table('teachers')->insert([
                'name' => $t['name'],
                'uuid' => $t['uuid'],
                'classroom' => $t['classroom'],
                'class_name' => $t['class'],
                'updated_at' => now(),
                'created_at' => now(),
            ]);
        }
    }
}
